In [ ]:
#Importando a biblioteca pandas e renomeando ela para 'pd'.
import pandas as pd

In [ ]:
#Trazendo a nossa base de dados do github e armazenando ela em uma variável chamada 'url'.
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
#Lendo a nossa base de dados e mostrando na tela.
pd.read_csv(url)

      Tipo;Bairro;Quartos;Vagas;Suites;Area;Valor;Condominio;IPTU
0              Quitinete;Copacabana;1;0;0;40;1700;500;60
1                  Casa;Jardim Botânico;2;0;1;100;7000;;
2      Conjunto Comercial/Sala;Barra da Tijuca;0;4;0;...
3                 Apartamento;Centro;1;0;0;15;800;390;20
4             Apartamento;Higienópolis;1;0;0;48;800;230;
...                                                  ...
32955               Quitinete;Centro;0;0;0;27;800;350;25
32956       Apartamento;Jacarepaguá;3;1;2;78;1800;800;40
32957  Apartamento;São Francisco Xavier;2;1;0;48;1400...
32958              Apartamento;Leblon;2;0;0;70;3000;760;
32959  Conjunto Comercial/Sala;Centro;0;0;0;250;6500;...

[32960 rows x 1 columns]

In [ ]:
#Mostrando a base de dados novamente e aplicando uma melhor formatação para análise
dados = pd.read_csv(url, sep=';')
#Verificando se a variável foi salva corretamente

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [ ]:
#Exibindo as 10 primeiras linhas da nossa base de dados (a contagem sempre se inicia a partir do zero)
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0

In [15]:
#Exibindo as 10 últimas linhas da nossa base de
dados.tail(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
32950,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
32951,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
32952,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
32953,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
32954,Box/Garagem,Centro,0,0,0,755,14000.0,NaN,NaN
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

Para uma melhor análise, é recomendado que utilize o "head" e "tail".
Eles ajudam a realizar uma análise exploratória sólida e menor confusa.

In [ ]:
#Para saber o tipo de uma variável, basta utilizar o 'type'
type(dados)

pandas.core.frame.DataFrame

In [17]:
#O primeiro elemento demonstra a quantidade de linhas do dataframe e o segundo elemento representa a quantidade de colunas
dados.shape

(32960, 9)

In [18]:
#O 'columns' mostra o nome das 9 colunas do nosso dataset
dados.columns

Index(['Tipo', 'Bairro', 'Quartos', 'Vagas', 'Suites', 'Area', 'Valor',
       'Condominio', 'IPTU'],
      dtype='object')

In [19]:
#O método 'info' nós trás informações além do tipo de dado de cada coluna
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [20]:
#Buscando dados específicos de uma coluna
dados['Tipo']

0                      Quitinete
1                           Casa
2        Conjunto Comercial/Sala
3                    Apartamento
4                    Apartamento
                  ...
32955                  Quitinete
32956                Apartamento
32957                Apartamento
32958                Apartamento
32959    Conjunto Comercial/Sala
Name: Tipo, Length: 32960, dtype: object

Percebemos que os dados nomeados como "object" são do tipo String.

In [24]:
#Buscando os dados das colunas 'Quartos' e 'Valor' no dataset
dados[['Quartos','Valor']]

       Quartos   Valor
0            1  1700.0
1            2  7000.0
2            0  5200.0
3            1   800.0
4            1   800.0
...        ...     ...
32955        0   800.0
32956        3  1800.0
32957        2  1400.0
32958        2  3000.0
32959        0  6500.0

[32960 rows x 2 columns]

Realizando mais uma análise, percebemos que dados do tipo "int64" são representados por números inteiros, e dados do tipo "float" são números decimais.